project:
  type: website
  output-dir: docs

website:
  title: "Yuying Lu" 
  navbar:
    pinned: true         
    collapse: true       
    background: "#ffffff"
    foreground: "#111111" 
    border: true          
    left:
      - href: index.qmd
        text: HOME
      - href: projects.qmd
        text: PROJECTS
      - href: publications.qmd
        text: PUBLICATIONS
      - href: experience.qmd
        text: EXPERIENCE

format:
  html:
    theme: cosmo         
    css: styles.css      
    toc: false            
    fontsize: 0.9em      
    linestretch: 1.5    