project:
  type: website
  output-dir: docs

website:
  title: "Yuying Lu" 
  navbar:
    pinned: true         
    collapse: true       
    background: "#ffffff"
    foreground: "#111111" 
    border: true          
    left:
      - href: index.qmd
        text: HOME
      - href: research.qmd
        text: RESEARCH
      - href: publications.qmd
        text: PUBLICATIONS
      - href: teaching.qmd
        text: TEACHING

format:
  html:
    theme: cosmo         
    css: styles.css      
    toc: false            
    fontsize: 1.1em      
    linestretch: 1.5    